version: '3.4'

services:

  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: src/UserApi/.
      dockerfile: Dockerfile
    networks:
        - rabbitmq_go_net
    environment:
      - RabbitMqConfig__Host=rabbitmq-server

  rabbitmq-server:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
